brand_name:
  default: 'ICIJ'
website_url:
  default: '/'
logo_url:
  default: 'https://www.icij.org/app/themes/icij/dist/images/favicons/apple-touch-icon-114x114_2dddab2f.png'
mobile_logo_url:
  default: ''
links:
  type: list
  default: ''
icons:
  type: list
  default: ''
custom_font_awesome_icons:
  type: list
  default: ''
